sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-107.pdf --upload --lsstdoc DMTN-107.tex --env=travis --ltd-product dmtn-107"
env:
  global:
    # Add LSST the Docs credentials
    - secure: "GBxMzQsSPO+M0WlPJYN0jYLQHNUCZwjS6kEm0m+sMtuntPGBxRGNI2sO+AvavOaPnmLeaw7FhZ4YBHOikZxTRyKPx9zGLWXb2wTM/h/6BfG8SuGq2J8tSgsI8zRoNeuCi7of0SnYIpFeWoFTShZYsWk3NonlIuNoCQhCpnY8+15k6AjRPtv1V7G/jc8Z1wWvWDtbISGHpjgWGg+4DH6QqP5RTY4iXgZTMfxNyemJUWmd7Mb1o/vwXQQuO2BJjcgf/4czFb/aNxBVz75BRf57eJs6Sx9XHTJoPHMKskk9v7t0heoaKGZAilMbyhkFsPszsuHhnxGzHuKww6wdRsdfAJd2prrh28ue5ziGBWBrcGOogOYrI+bMzzIiu51c+2bHzOlk/lP5Ds9TIuebIymrTm1O1Fg5VwSBDreT+sTXg2ix2C1qFrUnNhtSG4Kq3l1qyhg2sI0BU3wKj+3yBLqLUCnz89yHqZcxE+tdwd/VWWYtvTfhxRAgAgsx+oZB6oSu8QUesW3TaWyz2HrIKPzCPaHhHsCixYr+YICDAJS9hpvqWyjpxZuR6gwPzgZkHWUPVnGQnInT9fYiQMnCd4vdrnD6fHIaveNJZL35eBIvEgtUNZXuhc/AhIlcp6KuaWMo3b6b57bqyle3+bxpXNUdt3mRg+x4Z2/K9Kbg9YL4ve8="
    - secure: "hDjg/jYGMn42vysrXL3PGTeOoob4TaXfF+pzKBONGBtLM+tfz6HvZoDVH43CoMo7m5HZZjCwWTvTgfYZRMY4bZHJ7rU+sSZQJ4X5N7oWNBSVnQ6e0U9g+gu6n2E2Kd1cn2j4AzuXnBy4eyKmDwbP7GfAuCTlV/QjGhAKvouYflFKvpOqmdnJoPVGXx2Ybw1+P2upzU0kQ0BPWfTsZ0RAO4rsViYDZCq26dTS3HRyQR9Wq4dACdXPVE+LWy373iK+HNgJC812iybq7Dvqvu6DhvZELf+pZFG7BJDq5k/9b2nJHvzdRlY+Ven9e8Sw0Rx86zUsacx605TMTHkG+9FpRXp4LNTG9Stor+Y8AObMjRVuP16/E4rsi5DxwoYcI0GF6tq6sUPX4Vv0PSuLJqOMFUuGuOsoiufiT5FtKzqdqjjpOeBAW3MsXxUAyNI9Wun37gE5hYq+b0Fn0K/TgM7HqMR4wZjqXYROKNOvH+FHeDu6fev/3YjfezYG1SFqsr+sfgQwsYoQkoTfDXgoXlTHTI+BMDq/dUij5p7m+2rtU1Wl7Q8VGRGGc9b5w8RmDFoIk+5eXy4NKi57a2Z80ZQ5qOOpLbLZ4JfEuzco4uSPuBgC4k4AchAi3L5n6iRGptBSFodEuh3kF4bPBugN+0zUybPqIt2DZfxGvnS8zyuFKSI="
